jobs:
  analyze:
    name: Analyze
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    - continue-on-error: true
      name: Autobuild
      uses: github/codeql-action/autobuild@v3
    - continue-on-error: true
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    strategy:
      fail-fast: false
name: CodeQL security static code analysis
on:
  repository_dispatch:
    types: trigger-ga___sast.yml
permissions:
  contents: read
