jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dorny/test-reporter@v1
      with:
        artifact: /test-report-(.*)-(.*)/
        name: 'Test report: $1 $2'
        path: '**/build/test-results/**/TEST-*.xml'
        reporter: java-junit
name: Test Report
on:
  repository_dispatch:
    types: trigger-ga___test-report.yml
